model:
  pipeline: "vqa"
  linguistic_embedding: ["glove", "HSRP"]
  visual_embedding: ["swin_l", "swin_b"]
  visual causal:
    # visual front-door causal intervention
    module: "VFCI"
    clusters: 512
  linguistic causal:
    # linguistic back-door causal intervention
    module: "LBCI"
  # Spatial-Temporal Transformer
  backbone: "STT"
  num_gcn_layers: 1
  embed_dim: 512
  num_layers: 3
  num_heads: 8
data:
  dataset_name: "SUTD-TrafficQA"


