data:
  dataset_name: "iu_xray"
  image_dir: "../../MRG/data/iu_xray/images"
  ann_path: "../../MRG/data/iu_xray/annotation.json"
  tokenizer: "ori"
  max_seq_length: 60
  threshold: 3
  num_workers: 2
  batch_size: 16

model:
  model: "baseline"
  embed_dim: 512
  num_heads: 8
  en_num_layers: 3
  de_num_layers: 3
  dropout: 0.1
  logit_layers: 1
  bos_idx: 0
  eos_idx: 0
  pad_idx: 0
  use_bn: 0
  drop_prob_lm: 0.5

sample:
  sample_method: "beam_search"
  length_penalty: ""
  diversity_lambda: 0.5
  suppress_UNK: 0
  beam_size: 3
  temperature: 1.0
  sample_n: 1
  group_size: 1
  output_logsoftmax: 1
  decoding_constraint: 0
  block_trigrams: 1

trainer: 
  epochs: 100
  result_dir: "results/mrg/iu_xray_baseline"
  record_dir: "records/mrg/iu_xray_baseline"
  save_period: 1
  metric: ['Bleu', 'Meteor', 'Rouge', 'Cider']
  monitor_mode: "max"
  monitor_metric: "BLEU_4"
  early_stop: 50
  display_port: 8099
  statistic_level: 1
  monitor_metric_curves: false
  monitor_report: false
  monitor_image: false

optim:
  loss_fn: "lm"
  optim: "Adam"
  lr_en: 5.e-5
  lr_de: 1.e-4
  weight_decay: 5.e-5
  amsgrad: true
  lr_scheduler: "StepLR"
  step_size: 50
  gamma: 0.1

other:
  task_name: "train_baseline_iuxray"  # you can name current running work
  seed: -1
  cuda: 3
  task: "mrg"
  load_model_path: ""
  resume: ""
