# loading the baseline
__base__: configs/mrg/baseline.yaml

model:
  model: "vlci"
  # visual deconfound module
  v_causal: true
  local_sample: 6
  v_causal_proj: false
  # linguistic deconfound module
  l_causal: true
  l_causal_proj: false
optim:
  optim: "Adam"
  lr_en: 1.e-5
  lr_de: 1.e-5
  # note that we should load the 
  # pre-trained model for causal finetuning
  load_model_path: ""

